[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "wasm32-unknown-unknown",
]

[output]
feature-depth = 1

[advisories]
yanked = "deny"
ignore = [
    "RUSTSEC-2024-0436", # paste
    "RUSTSEC-2026-0173", # proc-macro-error2
    "RUSTSEC-2026-0247" # bitmaps
]

[licenses]
allow = [
    # Permissive. no restrictions on combining with AGPL
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "Unlicense",
    "Unicode-3.0",
    # Weak copyleft. GPL-compatible per FSF, thus AGPL-3.0-compatible
    "MPL-2.0",
    # "LGPL-2.1-or-later",
    # AGPL itself. for potential AGPL-licensed dependencies
    # "AGPL-3.0",
    # "AGPL-3.0-only",
    "AGPL-3.0-or-later",
]
confidence-threshold = 0.9

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
# wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/compio-rs/compio"]
